name: Test and Format Deno Template

on:
  [push, pull_request]

jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
          deno-version: 1.0.5
      - name: Test Deno Template
        run: deno test .
      - name: Format Deno Template
        run: deno fmt .